from story import *
from storyline import *
main_story.main_story = Story()
main_story.intro(user.name)
main_story.shop()
main_story.forest(user.name)
main_story.impDialogue()
main_story.reed(user.name)
main_story.trollDialogue()
main_story.wolf_story()
main_story.WolfDialogue()
main_story.lich_story()
main_story.BoneDialogue()
main_story.wizard_story()
main_story.LichDialogue()
main_story.worm_story()
main_story.WizardDialogue()
main_story.medusa_story()
main_story.wormDialogue()
main_story.kary_story()
main_story.medusaDialogue()
main_story.kraken_story()
main_story.karyDialogue()
main_story.tiamat_story()
main_story.krakenDialogue()
main_story.tiamat_story()
main_story.tiamatDialogue()
main_story.chaos_story()
main_story.chaosDialogue()
main_story.end()