from classes import *
from actions import *

def intro():
    output("Once Upon a Time....")
    time.sleep(1)
    output("Long ago, peace was restored. Monsters were eliminated")
    time.sleep(1)
    output("The five main evil forces were locked up, Lich, Kary, Kraken, Tiamat, and their boss, Chaos")
    time.sleep(1)
    output("They once covered the war in darkness until, the light warrior beat them all")
    time.sleep(1)
    output("You forgot who you were after they escaped and wiped your memory")
    time.sleep(1)
    output(f"You are {name}, the famous light warrior that destroyed these evil forces")
    time.sleep(1)
    output("Upon the escape of the evils, they released numerous monsters to guard their castle")
    time.sleep(1)
    output("Go! defeat the five evils and restore the world once again!")
    time.sleep(1)
    output("I am only a spirit and can only do so much, so I have left my friend to help you")
    time.sleep(1)
    output("He is a mushroom that will guide you away from monsters")
    time.sleep(1)
    output("Here, take this wooden sword, you will need it")
    wooden.equip()
    time.sleep(1)
    output("I have to go now, but save the world!")
    time.sleep(2)
    output("TOAD: Hey Im Toad, I'm going to help you on your journey")
    time.sleep(1)
    output("TOAD: I don't know about you, but I'm Staaaaaarrrrrvviiiinnnnnngnggggg!")
    time.sleep(1)
    output(f"{name.upper()}: Same!, lets get something to eat")
    time.sleep(1)
    output("TOAD: I know a good place to get a drink around here. Follow me!")

def forest():
    output("TOAD: Lets try to stay clear from any monsters when we hike through this forest")
    output("TOAD: Oh! and by the way, let me teach you some magic before we continue")
    output("TOAD: Brace yourself!, I'm going to transfer a spell into you")
    output("qswdfasdfhasdfjasdkfjkadsfhasdfkadsfhasdfuasfjasdkfjkadsfhasdfuasifosifhasiohehsdfjasjkdfjkalsdfhaweuifhasodfhajsdfhjasfdsjkdfjkalsdfhaweuifhasodfhajsdfhjasfd")
    magic_num += 1
    output("TOAD: Alright!, I just transfered a fire spell into you. You can now use it in battle!")
forest()